spring.application.name=jwt-auth-demo

# MYSQL DATABASE (CREATE DATABASE spring_boot_db; IN MYSQL BEFORE RUN)
spring.datasource.url=jdbc:mysql://localhost:3306/spring_boot_db
spring.datasource.username=root
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT SECRET MUST BE LONG ENOUGH FOR HMAC SHA (AT LEAST 32 CHARACTERS FOR DEMO)
jwt.secret=MY_JWT_SECRET_KEY_FOR_STUDENT_DEMO_MUST_BE_LONG_32CHARS_MIN
jwt.expiration-ms=86400000
